var price = 5;
var newPrice = 9.95;
var bin = 4;
var octal = 8;
var hex = 0xA;
var bigInt = 5331610;
console.log(price);
console.log(newPrice);
console.log(bin);
console.log(octal);
console.log(hex);
console.log(bigInt);
